// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2xRg2ktgQGLbJu1sqR2Mv1WOb4W7bwJY',
    appId: '1:110921428685:web:46314f5b6ed42cac038384',
    messagingSenderId: '110921428685',
    projectId: 'auth-flutter-60de1',
    authDomain: 'auth-flutter-60de1.firebaseapp.com',
    storageBucket: 'auth-flutter-60de1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeV4Cpu6ooySvRm8kDpY8QokWAOt4dd30',
    appId: '1:110921428685:android:618ee6f94b1a91e5038384',
    messagingSenderId: '110921428685',
    projectId: 'auth-flutter-60de1',
    storageBucket: 'auth-flutter-60de1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpjkJJlTo6gRTq2wT0cXr3_oy6kiHASaE',
    appId: '1:110921428685:ios:32ee5fa1768ffc4f038384',
    messagingSenderId: '110921428685',
    projectId: 'auth-flutter-60de1',
    storageBucket: 'auth-flutter-60de1.appspot.com',
    iosClientId: '110921428685-m1spkm8ojr10lmkm7rpqiviv8f8s63ci.apps.googleusercontent.com',
    iosBundleId: 'com.example.bubbleTea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpjkJJlTo6gRTq2wT0cXr3_oy6kiHASaE',
    appId: '1:110921428685:ios:32ee5fa1768ffc4f038384',
    messagingSenderId: '110921428685',
    projectId: 'auth-flutter-60de1',
    storageBucket: 'auth-flutter-60de1.appspot.com',
    iosClientId: '110921428685-m1spkm8ojr10lmkm7rpqiviv8f8s63ci.apps.googleusercontent.com',
    iosBundleId: 'com.example.bubbleTea',
  );
}
